[package]
name = "libsecp256k1-sys"
version = "0.1.0"
authors = ["ubuntu"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "secp256k1"
path = "src/lib.rs"

[dependencies]

[build-dependencies]
bindgen = "0.55.1"
