[package]
name = "head-first"
version = "0.1.0"
authors = ["lesterli <lester123@live.cn>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
ring = "0.16.9"

merkle_tree = { package = "merkle_tree", path = "merkle-tree" }